### PR TITLE
Create radio interactor

### PR DESCRIPTION
**Pull request by elrickvm**
## Motivation

Radio Interactor will allow users to interact with radio elements.

### CODE REVIEW

**Review by cowboyd — APPROVED** [review]
@elrickvm looks good. Have you added a changeset?

**Comment by elrickvm** [comment]
@cowboyd I am not sure how to add that. Can you expand on how to?. And I will add it no problem.

**Comment by elrickvm** [comment]
Ok @cowboyd I see what you mean now. I looked around the repo a bit and saw that covector was added to the repo. So adding a `radio.md` file within the `.changes` folder should create the changeset if I understand this correctly.

**Comment by cowboyd** [comment]
@elrickvm looks like we'll have to upgrade BigTest `v0.14.0`

**Comment by elrickvm** [comment]
@cowboyd yes because we are failing on chrome driver version mismatched.

**Comment by wKich** [comment]
I updated chromedriver in package-lock file #31

**Comment by elrickvm** [comment]
@wKich Thanks. I am going to pull and rebase.

**Pull request merged**
