### PR TITLE
add initial storybook setup

### LINKED ISSUE #41: Missing readme
I think we need a readme?

Just a few sentences on what advantages interactors provides to material ui would be very helpful. And perhaps an example too of how it's used.

### PR DESCRIPTION
**Pull request by wKich**
## Motivation

Let's introduce Material-UI interactors and how users can use them for example in Storybook's `play` function.
Fix #41 

## Approach

Copy-paste material-ui examples from the official site as stories and then add some interactions

### CODE REVIEW

**Comment by wKich** [comment]
@minkimcello added a simple readme

**Review by cowboyd — APPROVED** [review]
This looks good to me. For it to work well in Safari, I think we should strongy consider https://github.com/thefrontside/interactors/issues/25

@cherewaty @jorgelainfiesta @minkimcello How should we integrate this into the new interactors website

**Comment by minkimcello** [comment]
i have [this](https://github.com/thefrontside/bigtest/pull/995) pr open to lightly introduce mui+storybook in the current interactors website

it was my understanding we were hoping that material ui will add mui to their website?

**Comment by cherewaty** [comment]
I can move this codebase to the new `interactors` monorepo basically at any point now, but I think we should merge this PR before taking that step.

**Comment by wKich** [comment]
@cherewaty merged, thanks for help

**Pull request merged**
